<RockSimDocument>
    <FileVersion>4</FileVersion>
    <DesignInformation>
        <RocketDesign>
            <Name>Rocket</Name>
            <StageCount>1</StageCount>
            <DisplayFlags>7</DisplayFlags>
            <ViewType>0</ViewType>
            <ViewStageCount>3</ViewStageCount>
            <ViewTypeEdit>0</ViewTypeEdit>
            <ViewStageCountEdit>3</ViewStageCountEdit>
            <ZoomFactor>0.0</ZoomFactor>
            <ZoomFactorEdit>0.0</ZoomFactorEdit>
            <ScrollPosX>0</ScrollPosX>
            <ScrollPosY>0</ScrollPosY>
            <ScrollPosXEdit>0</ScrollPosXEdit>
            <ScrollPosYEdit>0</ScrollPosYEdit>
            <ThreeDFlags>0</ThreeDFlags>
            <ThreeDFlagsEdit>0</ThreeDFlagsEdit>
            <LastSerialNumber>28</LastSerialNumber>
            <Stage3Mass>0.0</Stage3Mass>
            <Stage2Mass>0.0</Stage2Mass>
            <Stage1Mass>0.0</Stage1Mass>
            <Stage3CG>2138.8268331021454</Stage3CG>
            <Stage2CGAlone>0.0</Stage2CGAlone>
            <Stage1CGAlone>0.0</Stage1CGAlone>
            <Stage321CG>0.0</Stage321CG>
            <Stage32CG>0.0</Stage32CG>
            <CPCalcFlags>1</CPCalcFlags>
            <CPSimFlags>1</CPSimFlags>
            <UseKnownMass>0</UseKnownMass>
            <Stage3Parts>
                <NoseCone>
                    <KnownMass>871.4665302613696</KnownMass>
                    <Density>1050.0</Density>
                    <Material>Polystyrene</Material>
                    <Name>Nose cone</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>871.4665302613696</CalcMass>
                    <CalcCG>275.9458869722521</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>480.0</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>1</SerialNo>
                    <ShapeCode>3</ShapeCode>
                    <ConstructionType>1</ConstructionType>
                    <WallThickness>4.500000000000001</WallThickness>
                    <ShapeParameter>0.0</ShapeParameter>
                    <AttachedParts/>
                    <BaseDia>160.0</BaseDia>
                    <ShoulderLen>0.0</ShoulderLen>
                    <ShoulderOD>0.0</ShoulderOD>
                </NoseCone>
                <BodyTube>
                    <KnownMass>461.66332363032916</KnownMass>
                    <Density>1200.0</Density>
                    <Material>Polycarbonate (Lexan)</Material>
                    <Name>Polycarbonate Tube</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>461.66332363032916</CalcMass>
                    <CalcCG>130.0</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>260.0</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>2</SerialNo>
                    <OD>160.0</OD>
                    <ID>154.0</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>154.0</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <MassObject>
                            <KnownMass>4000.0</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Payload</Name>
                            <KnownCG>-125.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>-125.0</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>300.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>3</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                    </AttachedParts>
                </BodyTube>
                <BodyTube>
                    <KnownMass>1221.0</KnownMass>
                    <Density>958.7050344900001</Density>
                    <Material>Kraft phenolic</Material>
                    <Name>Body tube FORE</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>1</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>1166.9987355585238</CalcMass>
                    <CalcCG>335.0</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>670.0</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>4</SerialNo>
                    <OD>160.0</OD>
                    <ID>152.60000000000002</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>152.60000000000002</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <Ring>
                            <KnownMass>246.90661022894173</KnownMass>
                            <Density>2700.0</Density>
                            <Material>Aluminum</Material>
                            <Name>Bulkhead 1 _ Payload _ Main Chute</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>535.0</Xb>
                            <CalcMass>246.90661022894173</CalcMass>
                            <CalcCG>2.5</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>5.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>5</SerialNo>
                            <OD>152.60000000000002</OD>
                            <ID>0.0</ID>
                            <UsageCode>1</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <MassObject>
                            <KnownMass>180.0</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Shock cord 1</Name>
                            <KnownCG>145.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>145.0</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>110.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>6</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <Parachute>
                            <KnownMass>907.1847392</KnownMass>
                            <Density>0.006700000000000001</Density>
                            <Material>Ripstop nylon</Material>
                            <Name>Main Chute</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>80.0</Xb>
                            <CalcMass>1254.7507221331605</CalcMass>
                            <CalcCG>175.00000000000003</CalcCG>
                            <DensityType>1</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>350.00000000000006</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>7</SerialNo>
                            <Dia>4876.8</Dia>
                            <ShroudLineCount>6</ShroudLineCount>
                            <Thickness>0.0</Thickness>
                            <ShroudLineLen>300.0</ShroudLineLen>
                            <ChuteCount>1</ChuteCount>
                            <ShroudLineMassPerMM>0.0018</ShroudLineMassPerMM>
                            <ShroudLineMaterial>Elastic cord (round 2 mm, 1/16 in)</ShroudLineMaterial>
                            <DragCoefficient>0.97</DragCoefficient>
                        </Parachute>
                        <MassObject>
                            <KnownMass>10.8</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Shock cord 2</Name>
                            <KnownCG>590.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>590.0</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>80.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>8</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <Ring>
                            <KnownMass>246.90661022894173</KnownMass>
                            <Density>2700.0</Density>
                            <Material>Aluminum</Material>
                            <Name>Bulkhead 2 _ Egg Timer</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>246.90661022894173</CalcMass>
                            <CalcCG>2.5</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>5.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>9</SerialNo>
                            <OD>152.60000000000002</OD>
                            <ID>0.0</ID>
                            <UsageCode>1</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>0.0</KnownMass>
                            <Density>680.0</Density>
                            <Material>Cardboard</Material>
                            <Name>Recovery Coupler</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-195.0</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>185.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>370.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>10</SerialNo>
                            <OD>152.40000000000006</OD>
                            <ID>152.40000000000006</ID>
                            <UsageCode>4</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>246.90661022894173</KnownMass>
                            <Density>2700.0</Density>
                            <Material>Aluminum</Material>
                            <Name>Bulkhead 3</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>1460.1000000000001</Xb>
                            <CalcMass>246.90661022894173</CalcMass>
                            <CalcCG>2.5</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>1</LocationMode>
                            <Len>5.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>11</SerialNo>
                            <OD>152.60000000000002</OD>
                            <ID>0.0</ID>
                            <UsageCode>1</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                    </AttachedParts>
                </BodyTube>
                <BodyTube>
                    <KnownMass>37.128598617185645</KnownMass>
                    <Density>680.0</Density>
                    <Material>Cardboard</Material>
                    <Name>Body tube</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>37.128598617185645</CalcMass>
                    <CalcCG>27.5</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>55.0</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>12</SerialNo>
                    <OD>160.0</OD>
                    <ID>156.0</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>156.0</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <MassObject>
                            <KnownMass>3.6</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Shock cord 3</Name>
                            <KnownCG>-40.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>-40.0</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>40.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>13</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                    </AttachedParts>
                </BodyTube>
                <BodyTube>
                    <KnownMass>658.0</KnownMass>
                    <Density>950.0</Density>
                    <Material>Kraft phenolic</Material>
                    <Name>Body tube</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>1</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>339.5182012587564</CalcMass>
                    <CalcCG>180.0</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>360.0</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>14</SerialNo>
                    <OD>160.0</OD>
                    <ID>156.0</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>156.0</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <Parachute>
                            <KnownMass>81.45942013332251</KnownMass>
                            <Density>0.006700000000000001</Density>
                            <Material>Ripstop nylon</Material>
                            <Name>Drogue Chute</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>220.00000000000009</Xb>
                            <CalcMass>81.45942013332251</CalcMass>
                            <CalcCG>50.0</CalcCG>
                            <DensityType>1</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>100.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>15</SerialNo>
                            <Dia>1219.1999999999998</Dia>
                            <ShroudLineCount>6</ShroudLineCount>
                            <Thickness>0.0</Thickness>
                            <ShroudLineLen>300.0</ShroudLineLen>
                            <ChuteCount>1</ChuteCount>
                            <ShroudLineMassPerMM>0.0018</ShroudLineMassPerMM>
                            <ShroudLineMaterial>Elastic cord (round 2 mm, 1/16 in)</ShroudLineMaterial>
                            <DragCoefficient>0.97</DragCoefficient>
                        </Parachute>
                        <MassObject>
                            <KnownMass>18.0</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Shock cord 4</Name>
                            <KnownCG>140.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>140.0</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>140.00000000000003</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>16</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <MassObject>
                            <KnownMass>830.0000000000001</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Avionics</Name>
                            <KnownCG>309.99999999999983</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>309.99999999999983</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>48.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>17</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <Ring>
                            <KnownMass>258.0315710099441</KnownMass>
                            <Density>2700.0</Density>
                            <Material>Aluminum</Material>
                            <Name>Bulkhead 4</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>258.0315710099441</CalcMass>
                            <CalcCG>2.5</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>5.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>18</SerialNo>
                            <OD>156.0</OD>
                            <ID>0.0</ID>
                            <UsageCode>1</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                    </AttachedParts>
                </BodyTube>
                <Transition>
                    <KnownMass>500.0</KnownMass>
                    <Density>2700.0</Density>
                    <Material>Aluminum</Material>
                    <Name>Transition FORE</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>1</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>314.565518096875</CalcMass>
                    <CalcCG>59.540877485727385</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>120.0</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>19</SerialNo>
                    <ShapeCode>0</ShapeCode>
                    <ConstructionType>1</ConstructionType>
                    <WallThickness>2.0</WallThickness>
                    <ShapeParameter>0.0</ShapeParameter>
                    <AttachedParts/>
                    <FrontShoulderLen>0.0</FrontShoulderLen>
                    <RearShoulderLen>0.0</RearShoulderLen>
                    <FrontShoulderDia>0.0</FrontShoulderDia>
                    <RearShoulderDia>0.0</RearShoulderDia>
                    <FrontDia>160.0</FrontDia>
                    <RearDia>152.908</RearDia>
                </Transition>
                <BodyTube>
                    <KnownMass>6000.0</KnownMass>
                    <Density>7850.0</Density>
                    <Material>Steel</Material>
                    <Name>Tank</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>1</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>5448.448742803516</CalcMass>
                    <CalcCG>366.00000000000006</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>732.0000000000001</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>20</SerialNo>
                    <OD>152.908</OD>
                    <ID>148.908</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>148.908</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <BodyTube>
                            <KnownMass>6000.0</KnownMass>
                            <Density>680.0</Density>
                            <Material>Cardboard</Material>
                            <Name>Inner Tube - Engine Mass</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>-950.0000000000001</Xb>
                            <CalcMass>1083.8645451332166</CalcMass>
                            <CalcCG>840.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>1680.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>21</SerialNo>
                            <OD>153.0</OD>
                            <ID>149.0</ID>
                            <IsMotorMount>0</IsMotorMount>
                            <MotorDia>149.0</MotorDia>
                            <EngineOverhang>0.0</EngineOverhang>
                            <IsInsideTube>1</IsInsideTube>
                            <AttachedParts/>
                        </BodyTube>
                    </AttachedParts>
                </BodyTube>
                <Transition>
                    <KnownMass>526.0</KnownMass>
                    <Density>2700.0</Density>
                    <Material>Aluminum</Material>
                    <Name>Transition AFT</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>1</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>1179.1488042119377</CalcMass>
                    <CalcCG>226.72170038915334</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>450.0</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>22</SerialNo>
                    <ShapeCode>0</ShapeCode>
                    <ConstructionType>1</ConstructionType>
                    <WallThickness>2.0</WallThickness>
                    <ShapeParameter>0.0</ShapeParameter>
                    <AttachedParts/>
                    <FrontShoulderLen>0.0</FrontShoulderLen>
                    <RearShoulderLen>0.0</RearShoulderLen>
                    <FrontShoulderDia>0.0</FrontShoulderDia>
                    <RearShoulderDia>0.0</RearShoulderDia>
                    <FrontDia>152.908</FrontDia>
                    <RearDia>160.0</RearDia>
                </Transition>
                <BodyTube>
                    <KnownMass>707.3295859557427</KnownMass>
                    <Density>950.0</Density>
                    <Material>Kraft phenolic</Material>
                    <Name>Body tube AFT</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>707.3295859557427</CalcMass>
                    <CalcCG>375.0</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>750.0</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>23</SerialNo>
                    <OD>160.0</OD>
                    <ID>156.0</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>156.0</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <BodyTube>
                            <KnownMass>325.0</KnownMass>
                            <Density>680.0</Density>
                            <Material>Cardboard</Material>
                            <Name>Inner Tube Booster 1</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>21.747360985210076</CalcMass>
                            <CalcCG>200.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>107.0</RadialLoc>
                            <RadialAngle>3.141592653589793</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>400.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>24</SerialNo>
                            <OD>51.39999999999999</OD>
                            <ID>50.39999999999999</ID>
                            <IsMotorMount>1</IsMotorMount>
                            <MotorDia>50.39999999999999</MotorDia>
                            <EngineOverhang>0.0</EngineOverhang>
                            <IsInsideTube>1</IsInsideTube>
                            <AttachedParts/>
                        </BodyTube>
                        <BodyTube>
                            <KnownMass>600.0</KnownMass>
                            <Density>680.0</Density>
                            <Material>Cardboard</Material>
                            <Name>Inner Tube Engine</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>1031.517066392391</CalcMass>
                            <CalcCG>297.5999999999995</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>595.199999999999</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>25</SerialNo>
                            <OD>153.0</OD>
                            <ID>142.0</ID>
                            <IsMotorMount>1</IsMotorMount>
                            <MotorDia>142.0</MotorDia>
                            <EngineOverhang>0.0</EngineOverhang>
                            <IsInsideTube>1</IsInsideTube>
                            <AttachedParts/>
                        </BodyTube>
                        <BodyTube>
                            <KnownMass>325.0</KnownMass>
                            <Density>680.0</Density>
                            <Material>Cardboard</Material>
                            <Name>Inner Tube Boosters 2</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>21.747360985210076</CalcMass>
                            <CalcCG>200.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>107.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>400.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>26</SerialNo>
                            <OD>51.39999999999999</OD>
                            <ID>50.39999999999999</ID>
                            <IsMotorMount>1</IsMotorMount>
                            <MotorDia>50.39999999999999</MotorDia>
                            <EngineOverhang>0.0</EngineOverhang>
                            <IsInsideTube>1</IsInsideTube>
                            <AttachedParts/>
                        </BodyTube>
                        <CustomFinSet>
                            <KnownMass>1650.0</KnownMass>
                            <Density>2700.0</Density>
                            <Material>Aluminum</Material>
                            <Name>Freeform fin set</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>994.6800000000001</CalcMass>
                            <CalcCG>162.61672095548315</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.7853981633974483</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>2</FinishCode>
                            <SerialNo>27</SerialNo>
                            <FinCount>4</FinCount>
                            <RootChord>0.0</RootChord>
                            <TipChord>0.0</TipChord>
                            <SemiSpan>0.0</SemiSpan>
                            <SweepDistance>0.0</SweepDistance>
                            <Thickness>3.0</Thickness>
                            <ShapeCode>2</ShapeCode>
                            <TipShapeCode>0</TipShapeCode>
                            <TabLength>50.0</TabLength>
                            <TabDepth>0.0</TabDepth>
                            <TabOffset>0.0</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                            <PointList>290.0,0.0|290.0,30.0|274.99999999999994,130.0|124.99999999999997,130.0|0.0,30.0|0.0,0.0|</PointList>
                        </CustomFinSet>
                        <MassObject>
                            <KnownMass>1500.0</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Fill_Feed System</Name>
                            <KnownCG>-350.00000000000006</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>-350.00000000000006</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>310.00000000000006</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>28</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                    </AttachedParts>
                </BodyTube>
            </Stage3Parts>
            <Stage2Parts/>
            <Stage1Parts/>
        </RocketDesign>
    </DesignInformation>
</RockSimDocument>