<RockSimDocument>
    <FileVersion>4</FileVersion>
    <DesignInformation>
        <RocketDesign>
            <Name>Starship</Name>
            <StageCount>1</StageCount>
            <DisplayFlags>7</DisplayFlags>
            <ViewType>0</ViewType>
            <ViewStageCount>3</ViewStageCount>
            <ViewTypeEdit>0</ViewTypeEdit>
            <ViewStageCountEdit>3</ViewStageCountEdit>
            <ZoomFactor>0.0</ZoomFactor>
            <ZoomFactorEdit>0.0</ZoomFactorEdit>
            <ScrollPosX>0</ScrollPosX>
            <ScrollPosY>0</ScrollPosY>
            <ScrollPosXEdit>0</ScrollPosXEdit>
            <ScrollPosYEdit>0</ScrollPosYEdit>
            <ThreeDFlags>0</ThreeDFlags>
            <ThreeDFlagsEdit>0</ThreeDFlagsEdit>
            <LastSerialNumber>9</LastSerialNumber>
            <Stage3Mass>0.0</Stage3Mass>
            <Stage2Mass>0.0</Stage2Mass>
            <Stage1Mass>0.0</Stage1Mass>
            <Stage3CG>353.27657370089867</Stage3CG>
            <Stage2CGAlone>0.0</Stage2CGAlone>
            <Stage1CGAlone>0.0</Stage1CGAlone>
            <Stage321CG>0.0</Stage321CG>
            <Stage32CG>0.0</Stage32CG>
            <CPCalcFlags>1</CPCalcFlags>
            <CPSimFlags>1</CPSimFlags>
            <UseKnownMass>0</UseKnownMass>
            <Stage3Parts>
                <NoseCone>
                    <KnownMass>20.406136641183203</KnownMass>
                    <Density>680.0</Density>
                    <Material>Cardboard</Material>
                    <Name>Nose Cone</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>20.406136641183203</CalcMass>
                    <CalcCG>94.31005360156922</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>150.00000000000003</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>0</SerialNo>
                    <ShapeCode>1</ShapeCode>
                    <ConstructionType>1</ConstructionType>
                    <WallThickness>2.0</WallThickness>
                    <ShapeParameter>0.0</ShapeParameter>
                    <AttachedParts/>
                    <BaseDia>50.0</BaseDia>
                    <ShoulderLen>0.0</ShoulderLen>
                    <ShoulderOD>0.0</ShoulderOD>
                </NoseCone>
                <BodyTube>
                    <KnownMass>41.016633685268374</KnownMass>
                    <Density>680.0</Density>
                    <Material>Cardboard</Material>
                    <Name>Top Body tube</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>41.016633685268374</CalcMass>
                    <CalcCG>100.0</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>200.0</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>1</SerialNo>
                    <OD>50.0</OD>
                    <ID>46.0</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>46.0</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <Parachute>
                            <KnownMass>7.975950925286614</KnownMass>
                            <Density>0.006700000000000001</Density>
                            <Material>Ripstop nylon</Material>
                            <Name>Parachute</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>0.0</Xb>
                            <CalcMass>7.975950925286614</CalcMass>
                            <CalcCG>12.5</CalcCG>
                            <DensityType>1</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>25.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>2</SerialNo>
                            <Dia>300.0</Dia>
                            <ShroudLineCount>6</ShroudLineCount>
                            <Thickness>0.0</Thickness>
                            <ShroudLineLen>300.0</ShroudLineLen>
                            <ChuteCount>1</ChuteCount>
                            <ShroudLineMassPerMM>0.0018</ShroudLineMassPerMM>
                            <ShroudLineMaterial>Elastic cord (round 2 mm, 1/16 in)</ShroudLineMaterial>
                            <DragCoefficient>0.8</DragCoefficient>
                        </Parachute>
                        <MassObject>
                            <KnownMass>0.7200000000000001</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Shock cord</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>0.0</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>25.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>3</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                    </AttachedParts>
                </BodyTube>
                <Transition>
                    <KnownMass>15.381237631975655</KnownMass>
                    <Density>680.0</Density>
                    <Material>Cardboard</Material>
                    <Name>Transition</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>15.381237631975655</CalcMass>
                    <CalcCG>37.49999999999993</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>75.00000000000001</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>4</SerialNo>
                    <ShapeCode>0</ShapeCode>
                    <ConstructionType>1</ConstructionType>
                    <WallThickness>2.0</WallThickness>
                    <ShapeParameter>0.0</ShapeParameter>
                    <AttachedParts/>
                    <FrontShoulderLen>0.0</FrontShoulderLen>
                    <RearShoulderLen>0.0</RearShoulderLen>
                    <FrontShoulderDia>0.0</FrontShoulderDia>
                    <RearShoulderDia>0.0</RearShoulderDia>
                    <FrontDia>50.0</FrontDia>
                    <RearDia>50.0</RearDia>
                </Transition>
                <BodyTube>
                    <KnownMass>41.016633685268374</KnownMass>
                    <Density>680.0</Density>
                    <Material>Cardboard</Material>
                    <Name>Aft Body tube</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>41.016633685268374</CalcMass>
                    <CalcCG>100.0</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>200.0</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>5</SerialNo>
                    <OD>50.0</OD>
                    <ID>46.0</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>46.0</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <FinSet>
                            <KnownMass>9.180000000000001</KnownMass>
                            <Density>680.0</Density>
                            <Material>Cardboard</Material>
                            <Name>Trapezoidal fin set</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>9.180000000000001</CalcMass>
                            <CalcCG>37.5</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>2</FinishCode>
                            <SerialNo>6</SerialNo>
                            <FinCount>3</FinCount>
                            <RootChord>50.0</RootChord>
                            <TipChord>50.0</TipChord>
                            <SemiSpan>30.0</SemiSpan>
                            <SweepDistance>25.0</SweepDistance>
                            <Thickness>3.0</Thickness>
                            <ShapeCode>0</ShapeCode>
                            <TipShapeCode>0</TipShapeCode>
                            <TabLength>50.0</TabLength>
                            <TabDepth>0.0</TabDepth>
                            <TabOffset>0.0</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                        </FinSet>
                        <BodyTube>
                            <KnownMass>1.3832432453755872</KnownMass>
                            <Density>680.0</Density>
                            <Material>Cardboard</Material>
                            <Name>Inner Tube</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>1.3832432453755872</CalcMass>
                            <CalcCG>35.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>70.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>7</SerialNo>
                            <OD>19.0</OD>
                            <ID>18.0</ID>
                            <IsMotorMount>1</IsMotorMount>
                            <MotorDia>18.0</MotorDia>
                            <EngineOverhang>0.0</EngineOverhang>
                            <IsInsideTube>1</IsInsideTube>
                            <AttachedParts/>
                        </BodyTube>
                        <Ring>
                            <KnownMass>1.874588336397029</KnownMass>
                            <Density>680.0</Density>
                            <Material>Cardboard</Material>
                            <Name>Centering ring 1</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>1.874588336397029</CalcMass>
                            <CalcCG>1.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>2.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>8</SerialNo>
                            <OD>46.0</OD>
                            <ID>19.0</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>1.874588336397029</KnownMass>
                            <Density>680.0</Density>
                            <Material>Cardboard</Material>
                            <Name>Centering ring 2</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>60.0</Xb>
                            <CalcMass>1.874588336397029</CalcMass>
                            <CalcCG>1.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>2.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>9</SerialNo>
                            <OD>46.0</OD>
                            <ID>19.0</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                    </AttachedParts>
                </BodyTube>
            </Stage3Parts>
            <Stage2Parts/>
            <Stage1Parts/>
        </RocketDesign>
    </DesignInformation>
</RockSimDocument>